#!/usr/bin/env python
# ***************************************************************************
# *   Copyright (c) 2017-2023 by Pierre-Henri WUILLEMIN (LIP6)              *
# *   info_at_agrum_dot_org                                                 *
# *                                                                         *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the GNU General Public License as published by  *
# *   the Free Software Foundation; either version 2 of the License, or     *
# *   (at your option) any later version.                                   *
# *                                                                         *
# *   This program is distributed in the hope that it will be useful,       *
# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
# *   GNU General Public License for more details.                          *
# *                                                                         *
# *   You should have received a copy of the GNU General Public License     *
# *   along with this program; if not, write to the                         *
# *   Free Software Foundation, Inc.,                                       *
# *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
# ***************************************************************************
import sys
import traceback

from acttools.main_act import main
from acttools.utils import notif

if __name__ == "__main__":
  try:
    tc, tm, tp = main()
    if tc + tm + tp != 0:
      notif(f"Time spent in cmake : [{tc:0.3f}]s , make : [{tm:0.3f}]s and post : [{tp:0.3f}]s ")
  except KeyboardInterrupt:
    print("\n Shutdown requested...exiting \n")
    sys.exit(1)
  except Exception:
    traceback.print_exc(file=sys.stdout)
    sys.exit(1)
