#!/usr/bin/env python3
"""Phase 6.1 of the GUM_PUBLIC chantier (docs: md_docs/GUM_PUBLIC.md, §4/§6).

Question this answers: starting from the public-by-default policy decided
2026-08-18 (md_docs/GUM_PUBLIC.md §6 point 4), what is the exact candidate
set of `gum::` classes/structs still needing a `GUM_PUBLIC` decision -- i.e.
every declared class/struct under `namespace gum`, minus:

  - the exclusions already fixed by audit in §2.4 (vendored code under
    */external/**, generated parsers under */cocoR/**, internal namespaces:
    __sig__, __debug__, complexity, _rand_namespace_, detail, threadsSTL,
    threadsOMP, DBTranslators, ScheduleStorageMethod);
  - symbols already tagged PYGUM_PUBLIC / PYGUM_SHARED_PUBLIC / GUM_PUBLIC
    (the 155 classes/structs from Phase 1-5, found by scanning for the tag
    directly on the declaration line);
  - the 51 GUM_MAKE_ERROR-generated exceptions, covered in one shot by the
    macro definition itself (base/core/exceptions.h) rather than
    individually -- collected here from the macro's call sites, since the
    generated class bodies are invisible to a textual/regex scan.

Method: same header-scanning approach as derive_pygum_public.py (Phase 1) --
a brace-depth/namespace-stack scan, not a real C++ parser. Precision is
"right order of magnitude", not symbol-exact (md_docs/GUM_PUBLIC.md §2,
explicitly documented limitation of this same method, carried over here
rather than re-solved). Nested classes/structs (e.g. iterator types defined
inside a container) are recorded qualified by their enclosing *namespace*
only, not their enclosing class -- a known imprecision inherited from Phase
1, not new here.

Free functions are NOT attempted mechanically in this pass (unlike Phase 1,
which had generated SWIG call sites as ground truth): with no such ground
truth for the C++-only case, a header-declaration regex would be
substantially less reliable. Left to manual/Phase 6.2 review, flagged
explicitly in the output.

Usage:
    python derive_gum_public_phase6.py
    python derive_gum_public_phase6.py --json-out /tmp/gum_public_phase6.json

Read-only: does not modify the source tree.
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
AGRUM_SRC = REPO_ROOT / "src/agrum"
EXCEPTIONS_H = AGRUM_SRC / "base/core/exceptions.h"

# Directories excluded wholesale (md_docs/GUM_PUBLIC.md §2.4, block 1).
EXCLUDED_DIR_PARTS = {"external", "cocoR"}

# Namespace names excluded wholesale (md_docs/GUM_PUBLIC.md §2.4, block 2).
# Matched against any single component of the namespace stack, regardless
# of nesting depth.
EXCLUDED_NAMESPACES = {
    "__sig__", "__debug__", "complexity", "_rand_namespace_", "detail",
    "threadsSTL", "threadsOMP", "DBTranslators", "ScheduleStorageMethod",
}

CLASS_DECL_RE = re.compile(
    r'^\s*(?:template\s*<[^>]*>\s*)?(?:class|struct)\s+'
    r'(?:([A-Z_][A-Z0-9_]*)\s+)?'   # optional visibility macro tag
    r'([A-Za-z_]\w*)\s*(?:final\s*)?[:{;<]'
)
NAMESPACE_OPEN_RE = re.compile(r'\bnamespace\s+([A-Za-z_]\w*(?:::[A-Za-z_]\w*)*)\s*\{')
NAMESPACE_ANON_OPEN_RE = re.compile(r'\bnamespace\s*\{')

KNOWN_TAGS = {"PYGUM_PUBLIC", "PYGUM_SHARED_PUBLIC", "GUM_PUBLIC"}


def strip_line_comments(line: str, in_block: bool) -> tuple[str, bool]:
    """Strip `//` line comments and `/* ... */` block comments (including
    ones spanning multiple lines) from `line`, given whether we entered it
    already inside a block comment. Returns (clean_line, still_in_block).

    Found live: without this, a Doxygen @code example inside a /** */ block
    (BIFReader.h's `aSimpleListener`) matched CLASS_DECL_RE and got
    (briefly) tagged as if it were real code -- md_docs/GUM_PUBLIC.md
    doesn't document this specific trap, discovered during Phase 6.4."""
    out = []
    i, n = 0, len(line)
    while i < n:
        if in_block:
            end = line.find("*/", i)
            if end == -1:
                return "".join(out), True
            in_block = False
            i = end + 2
            continue
        if line[i:i + 2] == "/*":
            end = line.find("*/", i + 2)
            if end == -1:
                return "".join(out), True
            i = end + 2
            continue
        if line[i:i + 2] == "//":
            break
        out.append(line[i])
        i += 1
    return "".join(out), in_block


def is_excluded_path(header: Path) -> bool:
    parts = set(header.relative_to(AGRUM_SRC).parts)
    return bool(parts & EXCLUDED_DIR_PARTS)


def collect_gum_make_error_exceptions() -> set[str]:
    """Names generated by GUM_MAKE_ERROR *call sites* only -- excludes the
    macro's own #define line, whose first parameter is the literal token
    'TYPE', not a real exception name."""
    names = set()
    for raw_line in EXCEPTIONS_H.read_text(errors="replace").splitlines():
        if raw_line.lstrip().startswith("#define"):
            continue
        m = re.search(r'GUM_MAKE_ERROR\(\s*([A-Za-z_]\w*)\s*,', raw_line)
        if m:
            names.add(m.group(1))
    return names


def scan_headers() -> tuple[dict[str, dict], dict[str, list[dict]], dict[str, list[dict]]]:
    """Returns (all_classes, excluded_by_namespace, excluded_nested_or_doxygen) where:
    - all_classes: qualified name -> {"tag": str|None, "locations": [...]}
      (tag is the visibility macro already present, if any)
    - excluded_by_namespace: qualified name -> [locations] for symbols found
      under an excluded namespace (kept separately, for audit visibility)
    - excluded_nested_or_doxygen: qualified name -> [locations] for symbols
      that are either (a) nested inside another class/struct -- tagging a
      nested type with an export macro is meaningless at best, wrong at
      worst (found live: TreeCmp, PatternData, NeighborDegreeSort,
      _RunningIntersect_, briefly mistagged in Phase 6.4) -- or (b) guarded
      by #ifndef DOXYGEN_SHOULD_SKIP_THIS, an existing "not public API"
      signal the project already uses elsewhere (found live: Debug, whose
      tag broke the build because GUM_PUBLIC wasn't even in scope in the
      translation unit that hit it -- independently also not meant to be
      public, per its own guard).
    """
    all_classes: dict[str, dict] = {}
    excluded_ns: dict[str, list] = defaultdict(list)
    excluded_nested: dict[str, list] = defaultdict(list)

    headers = sorted(AGRUM_SRC.rglob("*.h"))
    for header in headers:
        name = header.name
        if name.endswith("_inl.h") or name.endswith("_tpl.h"):
            continue
        if is_excluded_path(header):
            continue
        try:
            lines = header.read_text(errors="replace").splitlines()
        except OSError:
            continue

        ns_stack: list[str] = []
        depth_stack: list[int] = []
        scope_stack: list[tuple[str, int]] = []  # ("namespace"|"class", depth_at_open), combined nesting order
        depth = 0
        in_block_comment = False
        doxygen_skip_depth = 0
        for lineno, raw_line in enumerate(lines, start=1):
            line, in_block_comment = strip_line_comments(raw_line, in_block_comment)
            stripped_raw = raw_line.strip()

            if stripped_raw.startswith("#ifndef DOXYGEN_SHOULD_SKIP_THIS"):
                doxygen_skip_depth += 1
            elif stripped_raw.startswith("#endif") and "DOXYGEN_SHOULD_SKIP_THIS" in stripped_raw:
                doxygen_skip_depth = max(0, doxygen_skip_depth - 1)

            ns_m = NAMESPACE_OPEN_RE.search(line)
            if ns_m:
                for part in ns_m.group(1).split("::"):
                    ns_stack.append(part)
                    depth_stack.append(depth)
                    scope_stack.append(("namespace", depth))
            elif NAMESPACE_ANON_OPEN_RE.search(line):
                ns_stack.append("<anon>")
                depth_stack.append(depth)
                scope_stack.append(("namespace", depth))

            cls_m = CLASS_DECL_RE.match(line)
            is_nested = bool(scope_stack) and scope_stack[-1][0] == "class"
            if cls_m and ns_stack and ns_stack[0] == "gum":
                tag, clsname = cls_m.group(1), cls_m.group(2)
                if tag not in KNOWN_TAGS:
                    tag = None  # some other all-caps token (e.g. a macro-based base), not a visibility tag
                qualified = "::".join(ns_stack + [clsname])
                relpath = str(header.relative_to(REPO_ROOT))
                loc = {"file": relpath, "line": lineno}

                if EXCLUDED_NAMESPACES & set(ns_stack):
                    excluded_ns[qualified].append(loc)
                elif is_nested or doxygen_skip_depth > 0:
                    excluded_nested[qualified].append(loc)
                else:
                    entry = all_classes.setdefault(qualified, {"tag": tag, "locations": []})
                    entry["locations"].append(loc)
                    if tag and not entry["tag"]:
                        entry["tag"] = tag

            # a class/struct that opens a real body (not a forward decl ending in ';') pushes a scope
            # -- checked against the *unstripped-of-terminator* match so `class Foo;` never pushes.
            if cls_m and not line.rstrip().endswith(";"):
                scope_stack.append(("class", depth))

            depth += line.count("{") - line.count("}")
            while depth_stack and depth < depth_stack[-1] + 1 and depth <= depth_stack[-1]:
                depth_stack.pop()
                ns_stack.pop()
            while scope_stack and depth < scope_stack[-1][1] + 1 and depth <= scope_stack[-1][1]:
                scope_stack.pop()

    return all_classes, excluded_ns, excluded_nested


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--json-out", type=Path,
                         default=REPO_ROOT / "md_docs/gum_public_phase6_candidates.json",
                         help="where to write the machine-readable result")
    args = parser.parse_args()

    print(f"Scanning headers under {AGRUM_SRC} ...")
    all_classes, excluded_ns, excluded_nested = scan_headers()
    print(f"  {len(all_classes)} qualified class/struct names found (namespace-qualified, gum:: subtree, exclusions applied)")
    print(f"  {len(excluded_ns)} additional names found under excluded internal namespaces (kept for audit, not candidates)")
    print(f"  {len(excluded_nested)} additional names excluded as nested-in-class or DOXYGEN_SHOULD_SKIP_THIS-guarded")

    gum_make_error_names = collect_gum_make_error_exceptions()
    print(f"  {len(gum_make_error_names)} GUM_MAKE_ERROR exception names collected from {EXCEPTIONS_H.relative_to(REPO_ROOT)}")

    already_tagged = {}
    candidates = {}
    covered_by_macro = {}
    seen_macro_names = set()
    for qualified, entry in all_classes.items():
        bare = qualified.rsplit("::", 1)[-1]
        if bare in gum_make_error_names:
            covered_by_macro[qualified] = entry
            seen_macro_names.add(bare)
        elif entry["tag"]:
            already_tagged[qualified] = entry
        else:
            candidates[qualified] = entry

    # Names generated by GUM_MAKE_ERROR are covered by the macro's own tag
    # regardless of whether a forward declaration gave them a textual
    # footprint in all_classes (most do; md_docs/GUM_PUBLIC.md §2.4 already
    # notes GUM_MAKE_ERROR-expanded bodies are invisible to textual scans).
    for missing_name in sorted(gum_make_error_names - seen_macro_names):
        covered_by_macro[f"gum::{missing_name}"] = {
            "tag": "PYGUM_SHARED_PUBLIC",
            "locations": [],
            "note": "no forward declaration found; covered via GUM_MAKE_ERROR macro definition only",
        }

    print(f"\nAlready tagged (PYGUM_PUBLIC/PYGUM_SHARED_PUBLIC/GUM_PUBLIC): {len(already_tagged)}")
    print(f"Covered via GUM_MAKE_ERROR macro (not individually taggable): {len(covered_by_macro)}")
    print(f"Phase 6 candidates (untagged, public-by-default review needed): {len(candidates)}")

    by_module = defaultdict(int)
    for qualified, entry in candidates.items():
        rel = entry["locations"][0]["file"]
        module = rel.split("/")[2] if rel.startswith("src/agrum/") else "?"
        by_module[module] += 1
    print("\nCandidates by module:")
    for module, count in sorted(by_module.items(), key=lambda kv: -kv[1]):
        print(f"  {module:10s}: {count:4d}")

    result = {
        "note": "Free functions not attempted mechanically in this pass -- see module docstring.",
        "counts": {
            "total_gum_classes_in_scope": len(all_classes),
            "already_tagged": len(already_tagged),
            "covered_by_gum_make_error": len(covered_by_macro),
            "candidates": len(candidates),
            "excluded_by_internal_namespace": len(excluded_ns),
            "excluded_nested_or_doxygen": len(excluded_nested),
        },
        "excluded_nested_or_doxygen": excluded_nested,
        "already_tagged": already_tagged,
        "covered_by_gum_make_error": sorted(covered_by_macro.keys()),
        "candidates": candidates,
        "excluded_by_internal_namespace": excluded_ns,
    }
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(result, indent=2, sort_keys=True))
    print(f"\nWrote {args.json_out}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
