include_directories(${AGRUM_INCLUDE_DIRS})
add_definitions(${AGRUM_DEFINITIONS})
set (CMAKE_CXX_FLAGS "${AGRUM_CXX_FLAGS} ${CMAKE_CXX_FLAGS}")

if (MSVC)
    set (CMAKE_CXX_FLAGS "/DNOMINMAX /bigobj /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /MP ${CMAKE_CXX_FLAGS}")
    set (CMAKE_C_FLAGS "/DNOMINMAX /bigobj /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /MP ${CMAKE_C_FLAGS}")
endif()

link_directories(${AGRUM_LIBRARY_DIRS})

