option(BUILD_SHARED_LIBS "shared|static libs" ON)

set(AGRUM_INLINING_POLICY "")#"-fno-inline-small-functions")

include (CheckCXXCompilerFlag)
set (WARNING_FLAGS "-Wall -pedantic")
check_cxx_compiler_flag("${WARNING_FLAGS}" _SUPPORT_WARNING_FLAGS)
if (_SUPPORT_WARNING_FLAGS)
  set (CMAKE_CXX_FLAGS "${WARNING_FLAGS} ${CMAKE_CXX_FLAGS}")
endif ()

find_package (CXX14)
if (CXX14_FOUND)
  set (AGRUM_CXX_FLAGS "${CXX14_FLAGS} ${AGRUM_CXX_FLAGS}" )
else ()
  message(FATAL_ERROR "** aGrUM error: aGrUM is now using C++14. Please find a compiler (for instance GCC) C++14 compliant")
endif ()

if(MINGW)
  set(WIN32_STYLE_FLAGS 0)
  set(UNIX_STYLE_FLAGS  1)
endif(MINGW)
if(UNIX)
  set(WIN32_STYLE_FLAGS 0)
  set(UNIX_STYLE_FLAGS  1)
endif(UNIX)

if("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
	set(AGRUM_PROCESSOR "64")
else("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
	set(AGRUM_PROCESSOR "32")
endif("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")

set(AGRUM_VERSION "${AGRUM_VERSION_MAJOR}.${AGRUM_VERSION_MINOR}.${AGRUM_VERSION_PATCH}")

#-DNOMINMAX is for this stupid mvsc (@todo should be added only if WINDOWS ?)

set(CMAKE_CXX_FLAGS_DEBUG " -DGUM_NO_INLINE -DNOMINMAX")
set(CMAKE_C_FLAGS_DEBUG " -DGUM_NO_INLINE -DNOMINMAX")

set(CMAKE_CXX_FLAGS_RELEASE "${AGRUM_OPTIMIZATION} -DNDEBUG ${AGRUM_INLINING_POLICY} -DNOMINMAX")
set(CMAKE_C_FLAGS_RELEASE "${AGRUM_OPTIMIZATION} -DNDEBUG ${AGRUM_INLINING_POLICY} -DNOMINMAX")

if ("${CMAKE_BUILD_TYPE}" STREQUAL "DEBUG")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pg -ggdb")
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -pg -ggdb")
  set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -pg -ggdb")
endif ()

if(WIN32)
  set(LIBRARY_OUTPUT_PATH ${AGRUM_BINARY_DIR})
endif(WIN32)
if(UNIX)
  set(LIBRARY_OUTPUT_PATH ${AGRUM_BINARY_DIR}/lib)
endif(UNIX)

if ("${CMAKE_VERBOSE_MAKEFILE}" STREQUAL "ON")
set(GUM_TRACE_ON FALSE)
endif ("${CMAKE_VERBOSE_MAKEFILE}" STREQUAL "ON")

set(CMAKE_CXX_FLAGS "${AGRUM_CXX_FLAGS} ${CMAKE_CXX_FLAGS}")
