if(MINGW)
  set(WIN32_STYLE_FLAGS 0)
  set(UNIX_STYLE_FLAGS  1)
endif(MINGW)
if(UNIX)
  set(WIN32_STYLE_FLAGS 0)
  set(UNIX_STYLE_FLAGS  1)
endif(UNIX)

if("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
	set(AGRUM_PROCESSOR "64")
else("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
	set(AGRUM_PROCESSOR "32")
endif("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")

set(AGRUM_VERSION "${AGRUM_VERSION_MAJOR}.${AGRUM_VERSION_MINOR}.${AGRUM_VERSION_PATCH}")

set(CMAKE_CXX_FLAGS_DEBUG "-Wall -pedantic -O0 -pg -DGUM_NO_INLINE")
set(CMAKE_C_FLAGS_DEBUG "-Wall  -pedantic -O0 -pg -DGUM_NO_INLINE")

set(CMAKE_CXX_FLAGS_RELEASE "-Wall ${AGRUM_OPTIMIZATION} -DNDEBUG ${AGRUM_INLINING_POLICY}")
set(CMAKE_C_FLAGS_RELEASE "-Wall${AGRUM_OPTIMIZATION} -DNDEBUG ${AGRUM_INLINING_POLICY}")

if (${CMAKE_BUILD_TYPE} STREQUAL "DEBUG")
  set(LIBAGRUM "agrum-dbg")
else (${CMAKE_BUILD_TYPE} STREQUAL "DEBUG")
  set(LIBAGRUM "agrum")
endif (${CMAKE_BUILD_TYPE} STREQUAL "DEBUG")

if(WIN32)
  set(LIBRARY_OUTPUT_PATH ${AGRUM_BINARY_DIR})
endif(WIN32)
if(UNIX)
  set(LIBRARY_OUTPUT_PATH ${AGRUM_BINARY_DIR}/lib)
endif(UNIX)

add_definitions("-DAGRUM_SRC_PATH=${AGRUM_SOURCE_DIR}")
