set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER i586-mingw32msvc-gcc)
set(CMAKE_CXX_COMPILER i586-mingw32msvc-g++)

set(CMAKE_FIND_ROOT_PATH /usr/i586-mingw32msvc)

set(CMAKE_FIND_ROOT_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_MODE_PROGRAM ONLY)