############################################################################
#   This file is part of the aGrUM/pyAgrum library.                        #
#                                                                          #
#   Copyright (c) 2005-2026 by                                             #
#       - Pierre-Henri WUILLEMIN(_at_LIP6)                                 #
#       - Christophe GONZALES(_at_AMU)                                     #
#                                                                          #
#   The aGrUM/pyAgrum library is free software; you can redistribute it    #
#   and/or modify it under the terms of either :                           #
#                                                                          #
#    - the GNU Lesser General Public License as published by               #
#      the Free Software Foundation, either version 3 of the License,      #
#      or (at your option) any later version,                              #
#    - the MIT license (MIT),                                              #
#    - or both in dual license, as here.                                   #
#                                                                          #
#   (see https://agrum.gitlab.io/articles/dual-licenses-lgplv3mit.html)    #
#                                                                          #
#   This aGrUM/pyAgrum library is distributed in the hope that it will be  #
#   useful, but WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,          #
#   INCLUDING BUT NOT LIMITED TO THE WARRANTIES MERCHANTABILITY or FITNESS #
#   FOR A PARTICULAR PURPOSE  AND NONINFRINGEMENT. IN NO EVENT SHALL THE   #
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER #
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,        #
#   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR  #
#   OTHER DEALINGS IN THE SOFTWARE.                                        #
#                                                                          #
#   See LICENCES for more details.                                         #
#                                                                          #
#   SPDX-FileCopyrightText: Copyright 2005-2026                            #
#       - Pierre-Henri WUILLEMIN(_at_LIP6)                                 #
#       - Christophe GONZALES(_at_AMU)                                     #
#   SPDX-License-Identifier: LGPL-3.0-or-later OR MIT                      #
#                                                                          #
#   Contact  : info_at_agrum_dot_org                                       #
#   homepage : http://agrum.gitlab.io                                      #
#   gitlab   : https://gitlab.com/agrumery/agrum                           #
#                                                                          #
############################################################################

import contextlib
import io
import sys
import unittest

import pyagrum as gum

from .pyAgrumTestSuite import pyAgrumTestCase, addTests


class ExceptionTracebackTestCase(pyAgrumTestCase):
  """
  pyAgrum installs a sys.excepthook (see wrappers/pyagrum/cmake/__init__.in.py)
  that strips the internal SWIG proxy frames (pyagrumcpp.py, mrfcpp.py, ...)
  from an uncaught exception's traceback: those frames are one-line
  pass-through calls generated by SWIG and carry no information useful to a
  pyAgrum user.
  """

  @staticmethod
  def _printedTraceback(callback):
    try:
      callback()
    except Exception:
      buffer = io.StringIO()
      with contextlib.redirect_stderr(buffer):
        sys.excepthook(*sys.exc_info())
      return buffer.getvalue()
    raise AssertionError("callback did not raise")

  def testFreeFunctionExceptionHidesGeneratedFrames(self):
    printed = self._printedTraceback(lambda: gum.fastBN("A[3"))
    self.assertIn("InvalidArgument", printed)
    self.assertNotIn("pyagrumcpp.py", printed)
    self.assertNotIn("fastPrototype", printed)

  def testMethodExceptionHidesGeneratedFrames(self):
    bn = gum.fastBN("A->B")
    printed = self._printedTraceback(lambda: bn.cpt("Z"))
    self.assertIn("NotFound", printed)
    self.assertNotIn("pyagrumcpp.py", printed)

  def testFilterSurvivesInfluenceDiagramSubmoduleImport(self):
    # Regression test: pyagrum used to have a submodule literally named "id"
    # (InfluenceDiagram), which became an attribute of the pyagrum module
    # once imported and shadowed the builtin id() relied on internally by
    # the traceback filter (raising "TypeError: 'module' object is not
    # callable" instead of the real error). It has since been renamed to
    # pyagrum.influence_diagram, removing that specific collision -- this
    # test still guards the filter against breaking when an unrelated lazy
    # submodule has been imported first.
    _ = gum.InfluenceDiagram  # triggers the lazy submodule import of pyagrum.influence_diagram
    printed = self._printedTraceback(lambda: gum.fastBN("A[3"))
    self.assertIn("InvalidArgument", printed)
    self.assertNotIn("TypeError", printed)
    self.assertNotIn("pyagrumcpp.py", printed)


ts = unittest.TestSuite()
addTests(ts, ExceptionTracebackTestCase)
