//
// Created by phw on 25/07/22.
//

#ifndef AGRUM_DBTRANSLATOR4NUMERICALDISCRETEVARIABLETESTSUITE_H
#define AGRUM_DBTRANSLATOR4NUMERICALDISCRETEVARIABLETESTSUITE_H

#endif   // AGRUM_DBTRANSLATOR4NUMERICALDISCRETEVARIABLETESTSUITE_H
