# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.6.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""pyagrum.credal_net module"""

import typing
# ## recursive import for typehints annotation
import pyagrum
# ## end of added by passForType (pyAgrum)

# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _cncpp
else:
    import _cncpp

import builtins as __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

import pyagrum.pyagrumcpp
class CredalNet(object):
    r"""

    Constructor used to create a CredalNet (step by step or with two BayesNet)

    CredalNet() -> CredalNet
        default constructor

    CredalNet(src_min_num,src_max_den) -> CredalNet

    Parameters
    ----------
    src_min_num : str or pyagrum.BayesNet
                The path to a BayesNet or the BN itself which contains lower probabilities.
    src_max_den : str or pyagrum.BayesNet
                The (optional) path to a BayesNet or the BN itself which contains upper probabilities.


    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    NodeType_Precise = _cncpp.CredalNet_NodeType_Precise
    NodeType_Credal = _cncpp.CredalNet_NodeType_Credal
    NodeType_Vacuous = _cncpp.CredalNet_NodeType_Vacuous
    NodeType_Indic = _cncpp.CredalNet_NodeType_Indic

    def __init__(self, *args):
        _cncpp.CredalNet_swiginit(self, _cncpp.new_CredalNet(*args))
    __swig_destroy__ = _cncpp.delete_CredalNet

    def addVariable(self, name: str, card: int) -> int:
        r"""

        Parameters
        ----------
        name : str
            the name of the new variable
        card: int
            the domainSize of the new variable

        Returns
        -------
        int
            the id of the new node

        """
        return _cncpp.CredalNet_addVariable(self, name, card)

    def addArc(self, tail: int, head: int) -> None:
        r"""

        Adds an arc between two nodes

        Parameters
        ----------
        tail :
            the id of the tail node
        head : int
            the id of the head node

        Raises
        ------
        pyagrum.InvalidDirectedCircle
            If any (directed) cycle is created by this arc
        pyagrum.InvalidNode
            If head or tail does not belong to the graph nodes
        pyagrum.DuplicateElement
            If one of the arc already exists

        """
        return _cncpp.CredalNet_addArc(self, tail, head)

    def setCPTs(self, id: int, cpt: "pyagrum.YetUnWrapped") -> None:
        r"""

        Warnings
        --------
        (experimental function) - Parameters to be wrapped


        Set the vertices of the credal sets (all of the conditionals) of a given node

        Parameters
        ----------
        id : int
            the NodeId of the node
        cpt    : tbw
            the vertices of every credal set (for each instantiation of the parents)

        Warnings
        --------
        DOES not change the BayesNet (s) associated to this credal net !

        """
        return _cncpp.CredalNet_setCPTs(self, id, cpt)

    def setCPT(self, *args) -> None:
        r"""

        Warnings
        --------
        (experimental function) - Parameters to be wrapped


        Set the vertices of one credal set of a given node (any instantiation index)

        Parameters
        ----------
        id : int
            the Id of the node
        entry : int
            the index of the instantiation (from 0 to K - 1) excluding the given node (only the parents are used to compute the index of the credal set)
        ins : pyagrum.Instantiation
            the Instantiation (only the parents matter to find the credal set index)
        cpt    : tbw
            the vertices of every credal set (for each instantiation of the parents)

        Warnings
        --------
        DOES not change the BayesNet(s) associated to this credal net !

        """
        return _cncpp.CredalNet_setCPT(self, *args)

    def fillConstraints(self, id: int, lower: tuple[float, ...], upper: tuple[float, ...]) -> None:
        r"""

        Set the interval constraints of the credal sets of a given node (all instantiations)

        Parameters
        ----------
        id : int
            The id of the node
        lower : list
            The lower value for each probability in correct order
        upper : list
            The upper value for each probability in correct order

        Warnings
        --------
        You need to call intervalToCredal when done filling all constraints.

        Warnings
        --------
        DOES change the BayesNet (s) associated to this credal net !

        """
        return _cncpp.CredalNet_fillConstraints(self, id, lower, upper)

    def fillConstraint(self, *args) -> None:
        r"""

        Set the interval constraints of a credal set of a given node (from an instantiation index)

        Parameters
        ----------
        id : int
            The id of the node
        entry : int
            The index of the instantiation excluding the given node (only the parents are used to compute the index of the credal set)
        ins : pyagrum.Instantiation
            The Instantiation
        lower : list
            The lower value for each probability in correct order
        upper : list
            The upper value for each probability in correct order

        Warnings
        --------
        You need to call intervalToCredal when done filling all constraints.

        Warnings
        --------
        DOES change the BayesNet (s) associated to this credal net !

        """
        return _cncpp.CredalNet_fillConstraint(self, *args)

    def instantiation(self, id: int) -> "pyagrum.Instantiation":
        r"""

        Get an Instantiation from a node id, usefull to fill the constraints of the network.

        bnet accessors / shortcuts.

        Parameters
        ----------
        id : int
            the id of the node we want an instantiation from

        Returns
        -------
        pyagrum.Instantiation
            the instantiation

        """
        return _cncpp.CredalNet_instantiation(self, id)

    def domainSize(self, id: int) -> int:
        r"""

        Parameters
        ----------
        id : int
            The id of the node

        Returns
        -------
        int
            The cardinality of the node

        """
        return _cncpp.CredalNet_domainSize(self, id)

    def bnToCredal(self, *args) -> None:
        r"""

        Perturbates the BayesNet provided as input for this CredalNet by generating intervals instead of point probabilities and then computes each vertex of each credal set.

        Parameters
        ----------
        beta : float
            The beta used to perturbate the network
        oneNet : bool
            used as a flag. Set to True if one BayesNet if provided with counts, to False if two BayesNet are provided; one with probabilities (the lower net) and one with denominators over the first modalities (the upper net)
        keepZeroes : bool
            used as a flag as whether or not - respectively True or False - we keep zeroes as zeroes. Default is False, i.e. zeroes are not kept

        """
        return _cncpp.CredalNet_bnToCredal(self, *args)

    def intervalToCredalWithFiles(self) -> None:
        r"""

        Warnings
        --------
        Deprecated : use intervalToCredal (lrsWrapper with no input / output files needed).


        Computes the vertices of each credal set according to their interval definition (uses lrs).

        Use this method when using a single BayesNet storing counts of events.

        """
        return _cncpp.CredalNet_intervalToCredalWithFiles(self)

    def intervalToCredal(self) -> None:
        r"""

        Computes the vertices of each credal set according to their interval definition (uses lrs).

        Use this method when using two BayesNet, one with lower probabilities and one with upper probabilities.

        """
        return _cncpp.CredalNet_intervalToCredal(self)

    def lagrangeNormalization(self) -> None:
        r"""

        Normalize counts of a BayesNet storing counts of each events such that no probability is 0.

        Use this method when using a single BayesNet storing counts of events. Lagrange normalization. This call is irreversible and modify counts stored by __src_bn.

        Doest not performs computations of the parameters but keeps normalized counts of events only. Call idmLearning to compute the probabilities (with any parameter value).

        """
        return _cncpp.CredalNet_lagrangeNormalization(self)

    def idmLearning(self, *args) -> None:
        r"""

        Learns parameters from a BayesNet storing counts of events.

        Use this method when using a single BayesNet storing counts of events. IDM model if s > 0, standard point probability if s = 0 (default value if none precised).

        Parameters
        ----------
        s : int
            the IDM parameter.
        keepZeroes : bool
            used as a flag as whether or not - respectively True or False - we keep zeroes as zeroes. Default is False, i.e. zeroes are not kept.

        """
        return _cncpp.CredalNet_idmLearning(self, *args)

    def approximatedBinarization(self) -> None:
        r"""

        Approximate binarization.

        Each bit has a lower and upper probability which is the lowest - resp. highest - over all vertices of the credal set. Enlarge the orignal credal sets and may induce huge imprecision.

        Warnings
        --------
        Enlarge the orignal credal sets and therefor induce huge imprecision by propagation. Not recommended, use MCSampling or something else instead

        """
        return _cncpp.CredalNet_approximatedBinarization(self)

    def saveBNsMinMax(self, min_path: str, max_path: str) -> None:
        r"""

        If this CredalNet was built over a perturbed BayesNet, one can save the intervals as two BayesNet.

        to call after bnToCredal(GUM_SCALAR beta) save a BN with lower probabilities and a BN with upper ones

        Parameters
        ----------
        min_path : str
            the path to save the BayesNet which contains the lower probabilities of each node X.
        max_path : str
            the path to save the BayesNet which contains the upper probabilities of each node X.

        """
        return _cncpp.CredalNet_saveBNsMinMax(self, min_path, max_path)

    def computeBinaryCPTMinMax(self) -> None:
        r"""

        Used with binary networks to speed-up L2U inference.

        Store the lower and upper probabilities of each node X over the 'True' modality.

        """
        return _cncpp.CredalNet_computeBinaryCPTMinMax(self)

    def src_bn(self) -> "pyagrum.BayesNet":
        r"""

        Returns
        -------
        pyagrum.BayesNet
            Returns a constant reference to the original BayesNet (used as a DAG, it's CPTs does not matter).

        """
        return _cncpp.CredalNet_src_bn(self)

    def current_bn(self) -> "pyagrum.BayesNet":
        r"""

        Returns
        -------
        pyagrum.BayesNet
            Returs a constant reference to the actual BayesNet (used as a DAG, it's CPTs does not matter).

        """
        return _cncpp.CredalNet_current_bn(self)

    def credalNet_currentCpt(self) -> "pyagrum.YetUnWrapped":
        r"""

        Warnings
        --------
        Experimental function - Return type to be wrapped

        Returns
        -------
        tbw
            a constant reference to the (up-to-date) CredalNet CPTs.

        """
        return _cncpp.CredalNet_credalNet_currentCpt(self)

    def credalNet_srcCpt(self) -> "pyagrum.YetUnWrapped":
        r"""

        Warnings
        --------
        Experimental function - Return type to be wrapped

        Returns
        -------
        tbw
            a constant reference to the (up-to-date) CredalNet CPTs.

        """
        return _cncpp.CredalNet_credalNet_srcCpt(self)

    def currentNodeType(self, id: int) -> int:
        r"""

        Parameters
        ----------
        id : int
            The constant reference to the choosen NodeId

        Returns
        -------
        pyagrum.CredalNet
            the type of the choosen node in the (up-to-date) CredalNet __current_bn if any, __src_bn otherwise.

        """
        return _cncpp.CredalNet_currentNodeType(self, id)

    def nodeType(self, id: int) -> int:
        r"""

        Parameters
        ----------
        id : int
            the constant reference to the choosen NodeId

        Returns
        -------
        pyagrum.CredalNet
            the type of the choosen node in the (up-to-date) CredalNet in __src_bn.

        """
        return _cncpp.CredalNet_nodeType(self, id)

    def epsilonMin(self) -> float:
        r"""

        Returns
        -------
        float
            a constant reference to the lowest perturbation of the BayesNet provided as input for this CredalNet.

        """
        return _cncpp.CredalNet_epsilonMin(self)

    def epsilonMax(self) -> float:
        r"""

        Returns
        -------
        float
            a constant reference to the highest perturbation of the BayesNet provided as input for this CredalNet.

        """
        return _cncpp.CredalNet_epsilonMax(self)

    def epsilonMean(self) -> float:
        r"""

        Returns
        -------
        float
            a constant reference to the average perturbation of the BayesNet provided as input for this CredalNet.

        """
        return _cncpp.CredalNet_epsilonMean(self)

    def isSeparatelySpecified(self) -> bool:
        r"""

        Returns
        -------
        bool
            True if this CredalNet is separately and interval specified, False otherwise.

        """
        return _cncpp.CredalNet_isSeparatelySpecified(self)

    def hasComputedBinaryCPTMinMax(self) -> bool:
        r"""

        Check whether the binary CPT min/max values have been computed.

        Returns
        -------
        bool
            True if binary CPT min/max have been computed (via the dedicated computation method)

        """
        return _cncpp.CredalNet_hasComputedBinaryCPTMinMax(self)

    def get_binaryCPT_min(self) -> "pyagrum.YetUnWrapped":
        r"""

        Warnings
        --------
        Experimental function - Return type to be wrapped

        Returns
        -------
        tbw
            a constant reference to the lower probabilities of each node X over the 'True' modality

        """
        return _cncpp.CredalNet_get_binaryCPT_min(self)

    def get_binaryCPT_max(self) -> "pyagrum.YetUnWrapped":
        r"""

        Warnings
        --------
        Experimental function - Return type to be wrapped

        Returns
        -------
        tbw
            a constant reference to the upper probabilities of each node X over the 'True' modality

        """
        return _cncpp.CredalNet_get_binaryCPT_max(self)

    def __repr__(self) -> str:
        return _cncpp.CredalNet___repr__(self)

    def __str__(self) -> str:
        return _cncpp.CredalNet___str__(self)

# Register CredalNet in _cncpp:
_cncpp.CredalNet_swigregister(CredalNet)
class CNMonteCarloSampling(object):
    r"""

    Class used for inferences in credal networks with Monte Carlo sampling algorithm.

    CNMonteCarloSampling(cn) -> CNMonteCarloSampling
        Parameters:
            - **cn** (*pyagrum.CredalNet*) -- a credal network

    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, credalNet: "CredalNet"):
        _cncpp.CNMonteCarloSampling_swiginit(self, _cncpp.new_CNMonteCarloSampling(credalNet))

        self._model=credalNet



    __swig_destroy__ = _cncpp.delete_CNMonteCarloSampling

    def makeInference(self) -> None:
        r"""

        Starts the inference.

        """
        return _cncpp.CNMonteCarloSampling_makeInference(self)

    def insertEvidenceFile(self, path: str) -> None:
        r"""

        Insert evidence from file.

        Parameters
        ----------
        path : str
            the path to the evidence file.

        """
        return _cncpp.CNMonteCarloSampling_insertEvidenceFile(self, path)

    def setEvidence(self, evidces):
      """
      Erase all the evidences and apply addEvidence(key,value) for every pairs in evidces.

      Parameters
      ----------
      evidces : dict[str,Union[int,str,list[float]]] or list[pyagrum.Tensor]
       a dict of "name:evidence" where name is a string (the name of the variable) and evidence is an integer (an index) or a string (a label) or a list of float (a likelihood).

      Raises
      ------
      pyagrum.InvalidArgument
         If one value is not a value for the node
       pyagrum.InvalidArgument
         If the size of a value is different from the domain side of the node
       pyagrum.FatalError
         If one value is a vector of 0s
       pyagrum.UndefinedElement
         If one node does not belong to the Bayesian network
      """
      if isinstance(evidces, dict):
        self.eraseAllEvidence()
        for k,v in evidces.items():
          self.addEvidence(k,v)
        return
      elif isinstance(evidces, list):#should be a list of Tensor
        self.eraseAllEvidence()
        for p in evidces:
          self.addEvidence(p)
        return
      raise TypeError("Parameter must be a dict or a list, not %s"%(type(evidces)))


    def setVerbosity(self, v: bool) -> None:
        r"""

        Parameters
        ----------
        v : bool
                verbosity

        """
        return _cncpp.CNMonteCarloSampling_setVerbosity(self, v)

    def setEpsilon(self, eps: float) -> None:
        r"""

        Parameters
        ----------
        eps : float
            the epsilon we want to use

        Raises
        ------
        pyagrum.OutOfBounds
            If eps<0

        """
        return _cncpp.CNMonteCarloSampling_setEpsilon(self, eps)

    def setMinEpsilonRate(self, rate: float) -> None:
        r"""

        Parameters
        ----------
        rate : float
            the minimal epsilon rate

        """
        return _cncpp.CNMonteCarloSampling_setMinEpsilonRate(self, rate)

    def setMaxIter(self, max: int) -> None:
        r"""

        Parameters
        ----------
        max : int
            the maximum number of iteration

        Raises
        ------
        pyagrum.OutOfBounds
            If max <= 1

        """
        return _cncpp.CNMonteCarloSampling_setMaxIter(self, max)

    def setMaxTime(self, timeout: float) -> None:
        r"""

        Parameters
        ----------
        tiemout : float
            stopping criterion on timeout (in seconds)

        Raises
        ------
        pyagrum.OutOfBounds
            If timeout<=0.0

        """
        return _cncpp.CNMonteCarloSampling_setMaxTime(self, timeout)

    def setPeriodSize(self, p: int) -> None:
        r"""

        Parameters
        ----------
        p : int
            number of samples between 2 stopping

        Raises
        ------
        pyagrum.OutOfBounds
            If p<1

        """
        return _cncpp.CNMonteCarloSampling_setPeriodSize(self, p)

    def verbosity(self) -> bool:
        r"""

        Returns
        -------
        bool
            True if the verbosity is enabled

        """
        return _cncpp.CNMonteCarloSampling_verbosity(self)

    def epsilon(self) -> float:
        r"""

        Returns
        -------
        float
            the value of epsilon

        """
        return _cncpp.CNMonteCarloSampling_epsilon(self)

    def minEpsilonRate(self) -> float:
        r"""

        Returns
        -------
        float
            the value of the minimal epsilon rate

        """
        return _cncpp.CNMonteCarloSampling_minEpsilonRate(self)

    def maxIter(self) -> int:
        r"""

        Returns
        -------
        int
            the criterion on number of iterations

        """
        return _cncpp.CNMonteCarloSampling_maxIter(self)

    def maxTime(self) -> float:
        r"""

        Returns
        -------
        float
            the timeout(in seconds)

        """
        return _cncpp.CNMonteCarloSampling_maxTime(self)

    def periodSize(self) -> int:
        r"""

        Returns
        -------
        int
            the number of samples between 2 stopping

        Raises
        ------
        pyagrum.OutOfBounds
            If p<1

        """
        return _cncpp.CNMonteCarloSampling_periodSize(self)

    def nbrIterations(self) -> int:
        r"""

        Returns
        -------
        int
            the number of iterations

        """
        return _cncpp.CNMonteCarloSampling_nbrIterations(self)

    def currentTime(self) -> float:
        r"""

        Returns
        -------
        float
            get the current running time in second (float)

        """
        return _cncpp.CNMonteCarloSampling_currentTime(self)

    def messageApproximationScheme(self) -> str:
        r"""

        Returns
        -------
        str
            the approximation scheme message

        """
        return _cncpp.CNMonteCarloSampling_messageApproximationScheme(self)

    def history(self) -> tuple[float, ...]:
        r"""

        Returns
        -------
        tuple
            the scheme history

        Raises
        ------
        pyagrum.OperationNotAllowed
            If the scheme did not performed or if verbosity is set to false

        """
        return _cncpp.CNMonteCarloSampling_history(self)

    def _asIApproximationSchemeConfiguration(self) -> "pyagrum.YetUnWrapped":
        return _cncpp.CNMonteCarloSampling__asIApproximationSchemeConfiguration(self)

    def setRepetitiveInd(self, flag: bool) -> None:
        r"""

        Parameters
        ----------
        flag : bool
            True if repetitive independence is to be used, false otherwise. Only usefull with dynamic networks.

        """
        return _cncpp.CNMonteCarloSampling_setRepetitiveInd(self, flag)

    def marginalMax(self, *args) -> "pyagrum.Tensor":
        r"""

        Get the upper marginals of a given node id.

        Parameters
        ----------
        id : int
            the node id which upper marginals we want.
        varName : str
            the variable name which upper marginals we want.

        Returns
        -------
        list
            a constant reference to this node upper marginals.

        Raises
        ------
          pyagrum.IndexError
            If the node does not belong to the Credal network

        """
        return _cncpp.CNMonteCarloSampling_marginalMax(self, *args)

    def marginalMin(self, *args) -> "pyagrum.Tensor":
        r"""

        Get the lower marginals of a given node id.

        Parameters
        ----------
        id : int
            the node id which lower marginals we want.
        varName : str
            the variable name which lower marginals we want.

        Returns
        -------
        list
            a constant reference to this node lower marginals.

        Raises
        ------
          pyagrum.IndexError
            If the node does not belong to the Credal network

        """
        return _cncpp.CNMonteCarloSampling_marginalMin(self, *args)

    def insertModalsFile(self, path: str) -> None:
        r"""

        Insert variables modalities from file to compute expectations.

        Parameters
        ----------
        path : str
            The path to the modalities file.

        """
        return _cncpp.CNMonteCarloSampling_insertModalsFile(self, path)

    def dynamicExpMax(self, varName: str) -> tuple[float, ...]:
        r"""

        Get the upper dynamic expectation of a given variable prefix.

        Parameters
        ----------
        varName : str
            the variable name prefix which upper expectation we want.

        Returns
        -------
        float
            a constant reference to the variable upper expectation over all time steps.

        """
        return _cncpp.CNMonteCarloSampling_dynamicExpMax(self, varName)

    def dynamicExpMin(self, varName: str) -> tuple[float, ...]:
        r"""

        Get the lower dynamic expectation of a given variable prefix.

        Parameters
        ----------
        varName : str
            the variable name prefix which lower expectation we want.

        Returns
        -------
        float
            a constant reference to the variable lower expectation over all time steps.

        """
        return _cncpp.CNMonteCarloSampling_dynamicExpMin(self, varName)

    def eraseAllEvidence(self) -> None:
        r"""

        Erase all inference related data to perform another one.

        You need to insert evidence again if needed but modalities are kept. You can insert new ones by using the appropriate method which will delete the old ones.

        """
        return _cncpp.CNMonteCarloSampling_eraseAllEvidence(self)

    def addEvidence(self, *args) -> None:
        r"""

        Add evidence for a variable in the credal network.

        Parameters
        ----------
        id_or_name : int | str
            the node id or name
        val_or_label : int | str
            the value index or label for the evidence

        """
        return _cncpp.CNMonteCarloSampling_addEvidence(self, *args)

    def CN(self) -> "pyagrum.CredalNet":
        r"""

        Return the credal network used by this inference engine.

        Returns
        -------
        pyagrum.CredalNet
            the credal network

        """
        return _cncpp.CNMonteCarloSampling_CN(self)

# Register CNMonteCarloSampling in _cncpp:
_cncpp.CNMonteCarloSampling_swigregister(CNMonteCarloSampling)
class CNLoopyPropagation(object):
    r"""

    Class used for inferences in credal networks with Loopy Propagation algorithm.

    CNLoopyPropagation(cn) -> CNLoopyPropagation
        Parameters:
          - **cn** (*pyagrum.CredalNet*) -- a Credal network

    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    InferenceType_nodeToNeighbours = _cncpp.CNLoopyPropagation_InferenceType_nodeToNeighbours
    InferenceType_ordered = _cncpp.CNLoopyPropagation_InferenceType_ordered
    InferenceType_randomOrder = _cncpp.CNLoopyPropagation_InferenceType_randomOrder

    def makeInference(self) -> None:
        r"""

        Starts the inference.

        """
        return _cncpp.CNLoopyPropagation_makeInference(self)

    def insertEvidenceFile(self, path: str) -> None:
        r"""

        Insert evidence from file.

        Parameters
        ----------
        path : str
            the path to the evidence file.

        """
        return _cncpp.CNLoopyPropagation_insertEvidenceFile(self, path)

    def inferenceType(self, *args) -> int:
        r"""

        Returns
        -------
        int
            the inference type

        """
        return _cncpp.CNLoopyPropagation_inferenceType(self, *args)

    def saveInference(self, path: str) -> None:
        r"""

        Saves marginals.

        Parameters
        ----------
        path : str
            The path to the file to save marginals.

        """
        return _cncpp.CNLoopyPropagation_saveInference(self, path)

    def __init__(self, credalNet: "CredalNet"):
        _cncpp.CNLoopyPropagation_swiginit(self, _cncpp.new_CNLoopyPropagation(credalNet))

        self._model=credalNet



    __swig_destroy__ = _cncpp.delete_CNLoopyPropagation

    def setEvidence(self, evidces):
      """
      Erase all the evidences and apply addEvidence(key,value) for every pairs in evidces.

      Parameters
      ----------
      evidces : dict[str,Union[int,str,list[float]]] or list[pyagrum.Tensor]
       a dict of "name:evidence" where name is a string (the name of the variable) and evidence is an integer (an index) or a string (a label) or a list of float (a likelihood).

      Raises
      ------
      pyagrum.InvalidArgument
         If one value is not a value for the node
       pyagrum.InvalidArgument
         If the size of a value is different from the domain side of the node
       pyagrum.FatalError
         If one value is a vector of 0s
       pyagrum.UndefinedElement
         If one node does not belong to the Bayesian network
      """
      if isinstance(evidces, dict):
        self.eraseAllEvidence()
        for k,v in evidces.items():
          self.addEvidence(k,v)
        return
      elif isinstance(evidces, list):#should be a list of Tensor
        self.eraseAllEvidence()
        for p in evidces:
          self.addEvidence(p)
        return
      raise TypeError("Parameter must be a dict or a list, not %s"%(type(evidces)))


    def setVerbosity(self, v: bool) -> None:
        r"""

        Parameters
        ----------
        v : bool
                verbosity

        """
        return _cncpp.CNLoopyPropagation_setVerbosity(self, v)

    def setEpsilon(self, eps: float) -> None:
        r"""

        Parameters
        ----------
        eps : float
            the epsilon we want to use

        Raises
        ------
        pyagrum.OutOfBounds
            If eps<0

        """
        return _cncpp.CNLoopyPropagation_setEpsilon(self, eps)

    def setMinEpsilonRate(self, rate: float) -> None:
        r"""

        Parameters
        ----------
        rate : float
            the minimal epsilon rate

        """
        return _cncpp.CNLoopyPropagation_setMinEpsilonRate(self, rate)

    def setMaxIter(self, max: int) -> None:
        r"""

        Parameters
        ----------
        max : int
            the maximum number of iteration

        Raises
        ------
        pyagrum.OutOfBounds
            If max <= 1

        """
        return _cncpp.CNLoopyPropagation_setMaxIter(self, max)

    def setMaxTime(self, timeout: float) -> None:
        r"""

        Parameters
        ----------
        tiemout : float
            stopping criterion on timeout (in seconds)

        Raises
        ------
        pyagrum.OutOfBounds
            If timeout<=0.0

        """
        return _cncpp.CNLoopyPropagation_setMaxTime(self, timeout)

    def setPeriodSize(self, p: int) -> None:
        r"""

        Parameters
        ----------
        p : int
            number of samples between 2 stopping

        Raises
        ------
        pyagrum.OutOfBounds
            If p<1

        """
        return _cncpp.CNLoopyPropagation_setPeriodSize(self, p)

    def verbosity(self) -> bool:
        r"""

        Returns
        -------
        bool
            True if the verbosity is enabled

        """
        return _cncpp.CNLoopyPropagation_verbosity(self)

    def epsilon(self) -> float:
        r"""

        Returns
        -------
        float
            the value of epsilon

        """
        return _cncpp.CNLoopyPropagation_epsilon(self)

    def minEpsilonRate(self) -> float:
        r"""

        Returns
        -------
        float
            the value of the minimal epsilon rate

        """
        return _cncpp.CNLoopyPropagation_minEpsilonRate(self)

    def maxIter(self) -> int:
        r"""

        Returns
        -------
        int
            the criterion on number of iterations

        """
        return _cncpp.CNLoopyPropagation_maxIter(self)

    def maxTime(self) -> float:
        r"""

        Returns
        -------
        float
            the timeout(in seconds)

        """
        return _cncpp.CNLoopyPropagation_maxTime(self)

    def periodSize(self) -> int:
        r"""

        Returns
        -------
        int
            the number of samples between 2 stopping

        Raises
        ------
        pyagrum.OutOfBounds
            If p<1

        """
        return _cncpp.CNLoopyPropagation_periodSize(self)

    def nbrIterations(self) -> int:
        r"""

        Returns
        -------
        int
            the number of iterations

        """
        return _cncpp.CNLoopyPropagation_nbrIterations(self)

    def currentTime(self) -> float:
        r"""

        Returns
        -------
        float
            get the current running time in second (float)

        """
        return _cncpp.CNLoopyPropagation_currentTime(self)

    def messageApproximationScheme(self) -> str:
        r"""

        Returns
        -------
        str
            the approximation scheme message

        """
        return _cncpp.CNLoopyPropagation_messageApproximationScheme(self)

    def history(self) -> tuple[float, ...]:
        r"""

        Returns
        -------
        tuple
            the scheme history

        Raises
        ------
        pyagrum.OperationNotAllowed
            If the scheme did not performed or if verbosity is set to false

        """
        return _cncpp.CNLoopyPropagation_history(self)

    def _asIApproximationSchemeConfiguration(self) -> "pyagrum.YetUnWrapped":
        return _cncpp.CNLoopyPropagation__asIApproximationSchemeConfiguration(self)

    def setRepetitiveInd(self, flag: bool) -> None:
        r"""

        Parameters
        ----------
        flag : bool
            True if repetitive independence is to be used, false otherwise. Only usefull with dynamic networks.

        """
        return _cncpp.CNLoopyPropagation_setRepetitiveInd(self, flag)

    def marginalMax(self, *args) -> "pyagrum.Tensor":
        r"""

        Get the upper marginals of a given node id.

        Parameters
        ----------
        id : int
            the node id which upper marginals we want.
        varName : str
            the variable name which upper marginals we want.

        Returns
        -------
        list
            a constant reference to this node upper marginals.

        Raises
        ------
          pyagrum.IndexError
            If the node does not belong to the Credal network

        """
        return _cncpp.CNLoopyPropagation_marginalMax(self, *args)

    def marginalMin(self, *args) -> "pyagrum.Tensor":
        r"""

        Get the lower marginals of a given node id.

        Parameters
        ----------
        id : int
            the node id which lower marginals we want.
        varName : str
            the variable name which lower marginals we want.

        Returns
        -------
        list
            a constant reference to this node lower marginals.

        Raises
        ------
          pyagrum.IndexError
            If the node does not belong to the Credal network

        """
        return _cncpp.CNLoopyPropagation_marginalMin(self, *args)

    def insertModalsFile(self, path: str) -> None:
        r"""

        Insert variables modalities from file to compute expectations.

        Parameters
        ----------
        path : str
            The path to the modalities file.

        """
        return _cncpp.CNLoopyPropagation_insertModalsFile(self, path)

    def dynamicExpMax(self, varName: str) -> tuple[float, ...]:
        r"""

        Get the upper dynamic expectation of a given variable prefix.

        Parameters
        ----------
        varName : str
            the variable name prefix which upper expectation we want.

        Returns
        -------
        float
            a constant reference to the variable upper expectation over all time steps.

        """
        return _cncpp.CNLoopyPropagation_dynamicExpMax(self, varName)

    def dynamicExpMin(self, varName: str) -> tuple[float, ...]:
        r"""

        Get the lower dynamic expectation of a given variable prefix.

        Parameters
        ----------
        varName : str
            the variable name prefix which lower expectation we want.

        Returns
        -------
        float
            a constant reference to the variable lower expectation over all time steps.

        """
        return _cncpp.CNLoopyPropagation_dynamicExpMin(self, varName)

    def eraseAllEvidence(self) -> None:
        r"""

        Erase all inference related data to perform another one.

        You need to insert evidence again if needed but modalities are kept. You can insert new ones by using the appropriate method which will delete the old ones.

        """
        return _cncpp.CNLoopyPropagation_eraseAllEvidence(self)

    def addEvidence(self, *args) -> None:
        r"""

        Add evidence for a variable in the credal network.

        Parameters
        ----------
        id_or_name : int | str
            the node id or name
        val_or_label : int | str
            the value index or label for the evidence

        """
        return _cncpp.CNLoopyPropagation_addEvidence(self, *args)

    def CN(self) -> "pyagrum.CredalNet":
        r"""

        Return the credal network used by this inference engine.

        Returns
        -------
        pyagrum.CredalNet
            the credal network

        """
        return _cncpp.CNLoopyPropagation_CN(self)

# Register CNLoopyPropagation in _cncpp:
_cncpp.CNLoopyPropagation_swigregister(CNLoopyPropagation)

