# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.6.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""pyagrum.prm module"""

import typing
# ## recursive import for typehints annotation
import pyagrum
# ## end of added by passForType (pyAgrum)

# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _prm
else:
    import _prm

import builtins as __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

import pyagrum.pyagrum
class PRMexplorer(object):
    r"""

    PRMexplorer helps navigate through probabilistic relational models.

    PRMexplorer() -> PRMexplorer
        default constructor

    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""

        PRMexplorer helps navigate through probabilistic relational models.

        PRMexplorer() -> PRMexplorer
            default constructor

        """
        _prm.PRMexplorer_swiginit(self, _prm.new_PRMexplorer())
    __swig_destroy__ = _prm.delete_PRMexplorer

    def load(self, *args) -> None:
        r"""

        Load a PRM into the explorer.

        Parameters
        ----------
        filename : str
            the name of the o3prm file
        classpath : str
            the classpath of the PRM

        Raises
        ------
        pyagrum.FatalError
            If file not found

        """
        return _prm.PRMexplorer_load(self, *args)

    def isType(self, name: str) -> bool:
        r"""

        Parameters
        ----------
        name : str
            an element name

        Returns
        -------
        bool
            True if the parameter correspond to a type in the PRM

        """
        return _prm.PRMexplorer_isType(self, name)

    def isClass(self, name: str) -> bool:
        r"""

        Parameters
        ----------
        name : str
            an element name

        Returns
        -------
        bool
            True if the parameter correspond to a class in the PRM

        """
        return _prm.PRMexplorer_isClass(self, name)

    def isInterface(self, name: str) -> bool:
        r"""

        Parameters
        ----------
        name : str
            an element name

        Returns
        -------
        bool
            True if the parameter correspond to an interface in the PRM

        """
        return _prm.PRMexplorer_isInterface(self, name)

    def classes(self) -> list[str]:
        r"""

        Returns
        -------
        list
            the list of classes

        """
        return _prm.PRMexplorer_classes(self)

    def classAttributes(self, class_name: str) -> list[object]:
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        Returns
        -------
        list
            the list of attributes

        Raises
        ------
          pyagrum.IndexError
            If the class is not in the PRM

        """
        return _prm.PRMexplorer_classAttributes(self, class_name)

    def isAttribute(self, class_name: str, att_name: str) -> bool:
        r"""

        Parameters
        ----------
        class_name : str
            a class name
        att_name : str
            the name of the attribute to be tested

        Returns
        -------
        bool
            True if att_name is an attribute of class_name

        Raises
        ------
        pyagrum.IndexError
            If the class is not in the PRM
        pyagrum.IndexError
            If att_name is not an element of class_name

        """
        return _prm.PRMexplorer_isAttribute(self, class_name, att_name)

    def classReferences(self, class_name: str) -> list[object]:
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        Returns
        -------
        list
            the list of references

        Raises
        ------
        pyagrum.IndexError
            If the class is not in the PRM

        """
        return _prm.PRMexplorer_classReferences(self, class_name)

    def classParameters(self, class_name: str) -> list[str]:
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        Returns
        -------
        list
            the list of parameters

        Raises
        ------
          pyagrum.IndexError
            If the class is not in the PRM

        """
        return _prm.PRMexplorer_classParameters(self, class_name)

    def classImplements(self, class_name: str) -> list[str]:
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        Returns
        -------
        list
            the list of interfaces implemented by the class

        """
        return _prm.PRMexplorer_classImplements(self, class_name)
    aggType = property(_prm.PRMexplorer_aggType_get, _prm.PRMexplorer_aggType_set, doc=r"""

    min/max/count/exists/forall/or/and/amplitude/median

    """)

    def classAggregates(self, class_name: str) -> list[object]:
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        Returns
        -------
        list
            the list of aggregates in the class

        Raises
        ------
          pyagrum.IndexError
            If the class is not in the PRM

        """
        return _prm.PRMexplorer_classAggregates(self, class_name)

    def classSlotChains(self, class_name: str) -> list[object]:
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        Returns
        -------
        list
            the list of class slot chains

        Raises
        ------
        pyagrum.IndexError
            if the class is not in the PRM

        """
        return _prm.PRMexplorer_classSlotChains(self, class_name)

    def classDag(self, class_name: str) -> object:
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        Returns
        -------
        tuple
            a description of the DAG

        Raises
        ------
          pyagrum.IndexError
            If the class is not in the PRM

        """
        return _prm.PRMexplorer_classDag(self, class_name)

    def getalltheSystems(self) -> list[object]:
        r"""

        Returns
        -------
        list
            the list of all the systems and their components

        """
        return _prm.PRMexplorer_getalltheSystems(self)

    def getSuperClass(self, class_name: str) -> str | None:
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        Returns
        -------
        str
            the class extended by class_name

        Raises
        ------
        pyagrum.IndexError
            If the class is not in the PRM

        """
        return _prm.PRMexplorer_getSuperClass(self, class_name)

    def getDirectSubClass(self, class_name: str) -> list[str]:
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        Returns
        -------
        list
            the list of direct subclasses

        Raises
        ------
        pyagrum.IndexError
            If the class is not in the PRM

        """
        return _prm.PRMexplorer_getDirectSubClass(self, class_name)

    def cpf(self, class_name: str, attribute: str) -> "pyagrum.Tensor":
        r"""

        Parameters
        ----------
        class_name : str
            a class name

        attribute : str
            an attribute

        Returns
        -------
        pyagrum.Tensor
            the tensor of the attribute

        Raises
        ------
        pyagrum.OperationNotAllowed
            If the class element doesn't have any pyagrum.Tensor (like a pyagrum.PRMReferenceSlot).
        pyagrum.IndexError
            If the class is not in the PRM
        pyagrum.IndexError
            If the attribute in parameters does not exist

        """
        return _prm.PRMexplorer_cpf(self, class_name, attribute)

    def types(self) -> list[str]:
        r"""

        Returns
        -------
        list
            the list of the custom types in the PRM

        """
        return _prm.PRMexplorer_types(self)

    def getSuperType(self, type_name: str) -> str | None:
        r"""

        Parameters
        ----------
        type_name : str
            a type name

        Returns
        -------
        str
            the type extended by type_name

        Raises
        ------
        pyagrum.IndexError
            If the type is not in the PRM

        """
        return _prm.PRMexplorer_getSuperType(self, type_name)

    def getDirectSubTypes(self, type_name: str) -> list[str]:
        r"""

        Parameters
        ----------
        type_name : str
            a type name

        Returns
        -------
        list
            the list of direct subtypes

        Raises
        ------
        pyagrum.IndexError
            If the type is not in the PRM

        """
        return _prm.PRMexplorer_getDirectSubTypes(self, type_name)

    def getLabels(self, type_name: str) -> list[str]:
        r"""

        Parameters
        ----------
        type_name : str
            a type name

        Returns
        -------
        list
            the list of type labels

        Raises
        ------
        pyagrum.IndexError
            If the type is not in the PRM

        """
        return _prm.PRMexplorer_getLabels(self, type_name)

    def getLabelMap(self, type_name: str) -> object:
        r"""

        Parameters
        ----------
        type_name : str
            a type name

        Returns
        -------
        dict
            a dict containing pairs of label and their values

        Raises
        ------
        pyagrum.IndexError
            If the type is not in the PRM

        """
        return _prm.PRMexplorer_getLabelMap(self, type_name)

    def interfaces(self) -> list[str]:
        r"""

        Returns
        -------
        list
            the list of interfaces in the PRM

        """
        return _prm.PRMexplorer_interfaces(self)

    def interAttributes(self, interface_name: str, allAttributes: bool=False) -> list[object]:
        r"""

        Parameters
        ----------
        interface_name : str
            an interface

        allAttributes : bool
            True if supertypes of a custom type should be indicated

        Returns
        -------
        list
            the list of (<type>,<attribute_name>) for the given interface

        Raises
        ------
        pyagrum.IndexError
            If the type is not in the PRM

        """
        return _prm.PRMexplorer_interAttributes(self, interface_name, allAttributes)

    def interReferences(self, interface_name: str) -> list[object]:
        r"""

        Parameters
        ----------
        interface_name : str
            an interface

        Returns
        -------
        list
            the list of (<reference_type>,<reference_name>,<True if the reference is an array>) for the given interface

        Raises
        ------
        pyagrum.IndexError
            If the type is not in the PRM

        """
        return _prm.PRMexplorer_interReferences(self, interface_name)

    def getSuperInterface(self, interface_name: str) -> str | None:
        r"""

        Parameters
        ----------
        interface_name : str
            an interface name

        Returns
        -------
        str
            the interace extended by interface_name

        Raises
        ------
        pyagrum.IndexError
            If the interface is not in the PRM

        """
        return _prm.PRMexplorer_getSuperInterface(self, interface_name)

    def getDirectSubInterfaces(self, interface_name: str) -> list[str]:
        r"""

        Parameters
        ----------
        interface_name : str
            an interface name

        Returns
        -------
        list
            the list of direct subinterfaces

        Raises
        ------
        pyagrum.IndexError
            If the interface is not in the PRM

        """
        return _prm.PRMexplorer_getDirectSubInterfaces(self, interface_name)

    def getImplementations(self, interface_name: str) -> list[str]:
        r"""

        Parameters
        ----------
        interface_name : str
            an interface name

        Returns
        -------
        str
            the list of classes implementing the interface

        Raises
        ------
        pyagrum.IndexError
            If the interface is not in the PRM

        """
        return _prm.PRMexplorer_getImplementations(self, interface_name)

# Register PRMexplorer in _prm:
_prm.PRMexplorer_swigregister(PRMexplorer)

def _o3prm_loadBN(bn: "pyagrum.BayesNet", name: str, system: str, classpath: str, l: object) -> str:
    return _prm._o3prm_loadBN(bn, name, system, classpath, l)

def _o3prm_saveBN(bn: "pyagrum.BayesNet", name: str, allowModificationWhenSaving: bool) -> None:
    return _prm._o3prm_saveBN(bn, name, allowModificationWhenSaving)

def _bn_loadO3PRM(self, name, system="", classpath="", listeners=None):
  return _o3prm_loadBN(self, name, system, classpath, listeners)

def _bn_saveO3PRM(self, name, allowModificationWhenSaving=False):
  return _o3prm_saveBN(self, name, allowModificationWhenSaving)

# Monkeypatch onto the real core class, not the one SWIG would have generated
# for its own (unused) type reference in this module -- see the note above.
pyagrum.BayesNet.loadO3PRM = _bn_loadO3PRM
pyagrum.BayesNet.saveO3PRM = _bn_saveO3PRM


