############################################################################
#   This file is part of the aGrUM/pyAgrum library.                        #
#                                                                          #
#   Copyright (c) 2005-2026 by                                             #
#       - Pierre-Henri WUILLEMIN(_at_LIP6)                                 #
#       - Christophe GONZALES(_at_AMU)                                     #
#                                                                          #
#   The aGrUM/pyAgrum library is free software; you can redistribute it    #
#   and/or modify it under the terms of either :                           #
#                                                                          #
#    - the GNU Lesser General Public License as published by               #
#      the Free Software Foundation, either version 3 of the License,      #
#      or (at your option) any later version,                              #
#    - the MIT license (MIT),                                              #
#    - or both in dual license, as here.                                   #
#                                                                          #
#   (see https://agrum.gitlab.io/articles/dual-licenses-lgplv3mit.html)    #
#                                                                          #
#   This aGrUM/pyAgrum library is distributed in the hope that it will be  #
#   useful, but WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,          #
#   INCLUDING BUT NOT LIMITED TO THE WARRANTIES MERCHANTABILITY or FITNESS #
#   FOR A PARTICULAR PURPOSE  AND NONINFRINGEMENT. IN NO EVENT SHALL THE   #
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER #
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,        #
#   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR  #
#   OTHER DEALINGS IN THE SOFTWARE.                                        #
#                                                                          #
#   See LICENCES for more details.                                         #
#                                                                          #
#   SPDX-FileCopyrightText: Copyright 2005-2026                            #
#       - Pierre-Henri WUILLEMIN(_at_LIP6)                                 #
#       - Christophe GONZALES(_at_AMU)                                     #
#   SPDX-License-Identifier: LGPL-3.0-or-later OR MIT                      #
#                                                                          #
#   Contact  : info_at_agrum_dot_org                                       #
#   homepage : http://agrum.gitlab.io                                      #
#   gitlab   : https://gitlab.com/agrumery/agrum                           #
#                                                                          #
############################################################################

"""Generate the RST reference of all pyAgrum configuration keys from the defaults.ini schema.

Called by conf.py at the beginning of the Sphinx build; the result
(``generated/config-reference.inc``) is included by ``PyAgrumConfiguration.rst``.
"""

import os


def generate(outdir):
  import pyagrum

  bysection = {}
  deprecated = []
  for section, option, meta, default in pyagrum.config.schema():
    if meta.kind == "deprecated":
      deprecated.append((section, option, meta))
    else:
      bysection.setdefault(section, []).append((option, meta, default))

  lines = [
    ".. generated by gen_config_reference.py from pyagrum's defaults.ini -- do not edit",
    "",
  ]
  for section, entries in bysection.items():
    title = f"Section ``[{section}]``"
    lines += [title, "~" * len(title), ""]
    lines += [
      ".. list-table::",
      "   :header-rows: 1",
      "   :widths: 30 20 15 35",
      "",
      "   * - Key",
      "     - Type",
      "     - Default",
      "     - Description",
    ]
    for option, meta, default in entries:
      kind = "|".join(meta.values) if meta.kind == "enum" else meta.kind
      lines += [
        f"   * - ``{option}``",
        f"     - ``{kind}``",
        f"     - ``{default}``" if default != "" else "     - *(empty)*",
        f"     - {meta.doc}",
      ]
    lines.append("")

  title = "Deprecated keys"
  lines += [title, "~" * len(title), ""]
  if deprecated:
    lines += [
      ".. list-table::",
      "   :header-rows: 1",
      "   :widths: 30 30 40",
      "",
      "   * - Old key",
      "     - Replacement",
      "     - Note",
    ]
    for section, option, meta in deprecated:
      lines += [
        f"   * - ``{section}.{option}``",
        f"     - ``{meta.target[0]}.{meta.target[1]}``",
        f"     - {meta.doc}",
      ]
  else:
    lines.append("*(none)*")
  lines.append("")

  os.makedirs(outdir, exist_ok=True)
  with open(os.path.join(outdir, ".gitignore"), "w", encoding="utf-8") as f:
    f.write("*\n")
  with open(os.path.join(outdir, "config-reference.inc"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines))


if __name__ == "__main__":
  generate(os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated"))
